In [2]:
import numpy as np
arr = np.array([10, 11, 12, 13])
print(arr)

[10 11 12 13]


In [3]:
import numpy as np
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
import numpy as np
arr = np.zeros(2)
print(arr)

[0. 0.]


In [7]:
import numpy as np
arr = np.ones(4)
print(arr)

arr2 = np.ones(0)
print(arr2)

[1. 1. 1. 1.]
[]


In [8]:
import numpy as np
arr = np.arange(8)
print(arr)

[0 1 2 3 4 5 6 7]


In [10]:
import numpy as np
arr = np.arange(2,9)
print(arr)

arr2 = np.arange(2,9,2)
print(arr2)

[2 3 4 5 6 7 8]
[2 4 6 8]


In [17]:
y = np.ones(4,dtype=int)
print(y)
y

[1 1 1 1]


array([1, 1, 1, 1])

In [18]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [20]:
arr = np.array([1,2,3,4])
print(arr)
arr = np.delete(arr, 3)
print(arr)

[1 2 3 4]
[1 2 3]


In [22]:
arr = np.array([12,10,14,11,16])
print(arr)
arr = np.sort(arr)
print(arr)

[12 10 14 11 16]
[10 11 12 14 16]


In [24]:
arr = np.array([[11,12,13],[14,15,16]])
print(arr)
d = arr.ndim
print("dimensions = ",d)



[[11 12 13]
 [14 15 16]]
dimensions =  2


In [25]:
arr = np.array([[[1,2],[4,5]],[[6,7],[8,9]]])
print(arr)
d = arr.ndim
sizee = arr.size
print("dimensions = ",d)
print("Size = ",sizee)

[[[1 2]
  [4 5]]

 [[6 7]
  [8 9]]]
dimensions =  3
Size =  8


In [27]:
a = np.array(1)
b = np.array([1,2,3])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(a)
print("dimension of a = ",a.ndim)
print(b)
print("dimension of a = ",b.ndim)
print(c)
print("dimension of a = ",c.ndim)
print(d)
print("dimension of a = ",d.ndim)

1
dimension of a =  0
[1 2 3]
dimension of a =  1
[[1 2 3]
 [4 5 6]]
dimension of a =  2
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
dimension of a =  3


In [30]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr.shape)

(3, 4)


In [34]:
a = np.arange(4)
print(a)
b = a.reshape(2,2)
print(b)

[0 1 2 3]
[[0 1]
 [2 3]]
