In [1]:
import numpy as np
arr1 = np.array(8)
print("Array arr1 = ",arr1)
arr2 = np.array([10,20,30])
print("Array arr2 = ",arr2)

add = np.add(arr1,arr2)
print("Sum array = ",add)

sub = np.subtract(arr2,arr1)
print("Diff array = ",sub)

product = np.multiply(arr1,arr2)
print("Product array = ",product)

div = np.divide(arr2, arr1)
print("Division = ",div)

divby = np.divide(arr2,10)
print("Divide by a number = ",divby)

Array arr1 =  8
Array arr2 =  [10 20 30]
Sum array =  [18 28 38]
Diff array =  [ 2 12 22]
Product array =  [ 80 160 240]
Division =  [1.25 2.5  3.75]
Divide by a number =  [1. 2. 3.]


In [5]:
arr = np.array([0.5,2.2,3.3])
print(arr)

rec = np.reciprocal(arr)
print(rec)

[0.5 2.2 3.3]
[2.         0.45454545 0.3030303 ]


In [12]:
arr = np.array([2,4,5])
print("elements of arr = ",arr)

pow = np.power(arr,2)
print("power of elements of arr = ",pow)

arr2 = np.array([1,2,3])
pow2 = np.power(arr,arr2)
print("elemnts of array arr to the power of array arr2 = ",pow2)

elements of arr =  [2 4 5]
power of elements of arr =  [ 4 16 25]
elemnts of array arr to the power of array arr2 =  [  2  16 125]


In [15]:
arr1 = np.array([10,20,30])
arr2 = np.array([1,2,3])

print("arr1 = ",arr1)
print("arr2 = ",arr2)

m = np.mod(arr1,arr2)
print("values of mod = ",m)

rm = np.remainder(arr1, arr2)
print("values of remainder = ",rm)

arr1 =  [10 20 30]
arr2 =  [1 2 3]
values of mod =  [0 0 0]
values of remainder =  [0 0 0]


In [18]:
arr = np.array([10, 1.2j, 2 + 2.3j, -4.5j])
print(arr)

print("real = ",np.real(arr))
print("imaginary = ",np.imag(arr))
print("conjugate = ", np.conj(arr))

[10.+0.j   0.+1.2j  2.+2.3j -0.-4.5j]
real =  [10.  0.  2. -0.]
imaginary =  [ 0.   1.2  2.3 -4.5]
conjugate =  [10.-0.j   0.-1.2j  2.-2.3j -0.+4.5j]


In [21]:
arr = np.array([1.24, 2.34, 4.5 ,6.7])
print(arr)
print("after rounding up = ",np.around(arr))
print("after rounding up to 1st decimal place = ",np.around(arr,decimals = 1))

[1.24 2.34 4.5  6.7 ]
after rounding up =  [1. 2. 4. 7.]
after rounding up to 1st decimal place =  [1.2 2.3 4.5 6.7]


In [23]:
arr = np.array([1.2, 2.34, 4.66])
print(arr)
print(np.floor(arr))
print(np.ceil(arr))

[1.2  2.34 4.66]
[1. 2. 4.]
[2. 3. 5.]
